Smart contracts questions
DoDAO-io/dodao-defi-course pull request #19
Opened 2022-08-14 09:52 UTC by Lakshya18jul

2022-08-15 16:40 UTC, RobinNagpal requested changes

2022-08-15 16:40 UTC, RobinNagpal commented on src/questions/smart_contracts.yaml
> +  content: What does a Transaction mean in DeFi?
A Transaction is more of a generic concept that relates to modifying of the state on blockchain. 

Like adding information about NFTs can also be a transaction, but it doesn't involve transferring of tokens

2022-08-15 16:40 UTC, RobinNagpal commented on src/questions/smart_contracts.yaml
> +    - content: Ethereum is sent from one user to another directly.
We might have to update the options as option `A` is also partially correct. In sending of the tokens, the smart contract code is executed in a transaction behind the scenes

2022-08-15 16:40 UTC, RobinNagpal commented on src/questions/smart_contracts.yaml
> +  choices:
Important question. We just need to reword the choices for more clarity. See these two slides

<img width="579" alt="image" src="https://user-images.githubusercontent.com/745748/184656539-09ab03b3-6db6-4d3e-abfb-14afec4fdef1.png">

https://takenobu-hs.github.io/downloads/ethereum_evm_illustrated.pdf

2022-08-15 16:40 UTC, RobinNagpal commented on src/questions/smart_contracts.yaml
> +    - content: Irreversible
```suggestion
    - content: Irreversible once executed
```

2022-08-15 16:40 UTC, RobinNagpal commented on src/questions/smart_contracts.yaml
> +  explanation: An Ethereum account composes of majorly 4 fields. Those are nonce, balance, codeHash and storageRoot.
Great question. We should reword and ask `Which of the following is not part of account field`

2022-08-15 16:40 UTC, RobinNagpal commented on src/questions/smart_contracts.yaml
> +  content: Ethereum accommodates how many types of transactions?
```suggestion
  content: Ethereum accommodates which of the below types of transactions?
```

We should give the options as the types

2022-08-15 16:40 UTC, RobinNagpal commented on src/questions/smart_contracts.yaml
> +    - content: Switch to lightning network
We should give some other option instead of `lightning network` as it specific to bitcoin and is not applicable to all blockchains

2022-08-15 16:40 UTC, RobinNagpal commented on src/questions/smart_contracts.yaml
> +  content: How do “searchers” execute gas golfing? Gas golfing refers to programming transactions using the least amount of gas.
`gas golfing` is not present in summaries. Can you please include it there too if you feel this is an important thing.

2022-08-15 16:40 UTC, RobinNagpal commented on src/questions/smart_contracts.yaml
> +    - content: None of the above
```suggestion
    - content: ENTER CORRECT OPTION HERE
```

This will help user know about MEV

2022-08-15 16:40 UTC, RobinNagpal commented on src/questions/smart_contracts.yaml
> +    - content: MEV becomes greater than the standard block reward
We should expand on `MEV becomes greater than the standard block reward` how this is an ill effect, or reword it

2022-08-15 16:40 UTC, RobinNagpal commented on src/questions/smart_contracts.yaml
> +  type: SingleChoice
No so apt question and may be we can remove it.

2022-08-15 16:40 UTC, RobinNagpal commented on src/questions/smart_contracts.yaml
> +  content: Which of the following are two most important languages for coding the smart contract?
```suggestion
  content: Which of the following are two most important languages for coding the smart contracts on Ethereum?
```

2022-08-15 16:40 UTC, RobinNagpal commented on src/questions/smart_contracts.yaml
> +  content: What is the maximum limit of the size of smart contract?
```suggestion
  content: What is the maximum limit of the size of smart contract on Ethereum?
```

2022-08-15 16:40 UTC, RobinNagpal commented on src/questions/smart_contracts.yaml
> +    - content: 1.2 Gb
```suggestion
    - content: ~1.2 Gb
```

2022-08-15 16:40 UTC, RobinNagpal commented on src/questions/smart_contracts.yaml
> +    - content: 24 Kb
```suggestion
    - content: ~24 Kb
```

2022-08-15 16:40 UTC, RobinNagpal commented on src/questions/smart_contracts.yaml
> +    - content: 24 Kb
On [November 22, 2016](https://blog.ethereum.org/2016/11/18/hard-fork-no-4-spurious-dragon/) the Spurious Dragon hard-fork introduced [EIP-170](https://eips.ethereum.org/EIPS/eip-170) which added a smart contract size limit of 24.576 kb.

2022-08-15 16:40 UTC, RobinNagpal commented on src/questions/smart_contracts.yaml
> +    - content: A bot which communicates real-world events to the network
`    - content: A bot which communicates real-world events to the network` this option is partially correct. So we should may be reword it for clarity

2022-08-16 09:37 UTC, Lakshya18jul commented on src/questions/smart_contracts.yaml
> +  content: What does a Transaction mean in DeFi?
Made necessary changes

2022-08-16 09:40 UTC, Lakshya18jul commented on src/questions/smart_contracts.yaml
> +    - content: Ethereum is sent from one user to another directly.
Made the changes in options

2022-08-16 09:45 UTC, Lakshya18jul commented on src/questions/smart_contracts.yaml
> +  choices:
Made the changes

2022-08-16 09:45 UTC, Lakshya18jul commented on src/questions/smart_contracts.yaml
> +    - content: Irreversible
done

2022-08-16 09:49 UTC, Lakshya18jul commented on src/questions/smart_contracts.yaml
> +  explanation: An Ethereum account composes of majorly 4 fields. Those are nonce, balance, codeHash and storageRoot.
made relevant changes

2022-08-16 09:51 UTC, Lakshya18jul commented on src/questions/smart_contracts.yaml
> +  content: Ethereum accommodates how many types of transactions?
done

2022-08-16 09:52 UTC, Lakshya18jul commented on src/questions/smart_contracts.yaml
> +  content: How do “searchers” execute gas golfing? Gas golfing refers to programming transactions using the least amount of gas.
This was made so that users themselves some bit of research to get the answer. As the question is not very difficult.

2022-08-16 09:54 UTC, Lakshya18jul commented on src/questions/smart_contracts.yaml
> +    - content: Switch to lightning network
bitcoin has lightning network and etheruem uses plasma. This I reframed the option to switching to a paid speed network.

2022-08-16 09:56 UTC, Lakshya18jul commented on src/questions/smart_contracts.yaml
> +    - content: None of the above
DOne

2022-08-16 10:01 UTC, Lakshya18jul commented on src/questions/smart_contracts.yaml
> +    - content: MEV becomes greater than the standard block reward
Made a new option

2022-08-16 10:11 UTC, Lakshya18jul commented on src/questions/smart_contracts.yaml
> +  content: Which of the following are two most important languages for coding the smart contract?
Done

2022-08-16 10:12 UTC, Lakshya18jul commented on src/questions/smart_contracts.yaml
> +  content: What is the maximum limit of the size of smart contract?
Done

2022-08-16 10:13 UTC, Lakshya18jul commented on src/questions/smart_contracts.yaml
> +    - content: 24 Kb
Done

2022-08-16 10:19 UTC, Lakshya18jul commented on src/questions/smart_contracts.yaml
> +    - content: A bot which communicates real-world events to the network
Tried to introduce a wrong option

2022-08-16 10:24 UTC, Lakshya18jul commented on src/questions/smart_contracts.yaml
> +  type: SingleChoice
Added a new question

2022-08-16 10:25 UTC, closed without merging